spring:
  application:
    name: jwt-demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: scott
    password: xjh12345678
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 30000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: html
    encoding: utf-8
  #jpa相关配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        format_sql: true
server:
  port: 8080
mybatis:
  typeAliasesPackage: jwtdemo.*
  mapper-locations: classpath:mapper/*.xml